/*
 * This file is generated by jOOQ.
*/
package kobishop;


import javax.annotation.Generated;

import kobishop.tables.Account;
import kobishop.tables.Brand;
import kobishop.tables.Order;
import kobishop.tables.Product;
import kobishop.tables.Type;


/**
 * Convenience access to all tables in kobishop
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kobishop.account</code>.
     */
    public static final Account ACCOUNT = kobishop.tables.Account.ACCOUNT;

    /**
     * The table <code>kobishop.brand</code>.
     */
    public static final Brand BRAND = kobishop.tables.Brand.BRAND;

    /**
     * The table <code>kobishop.order</code>.
     */
    public static final Order ORDER = kobishop.tables.Order.ORDER;

    /**
     * The table <code>kobishop.product</code>.
     */
    public static final Product PRODUCT = kobishop.tables.Product.PRODUCT;

    /**
     * The table <code>kobishop.type</code>.
     */
    public static final Type TYPE = kobishop.tables.Type.TYPE;
}
