/*
 * This file is generated by jOOQ.
*/
package kobishop;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kobishop.tables.User;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kobishop extends SchemaImpl {

    private static final long serialVersionUID = -715581682;

    /**
     * The reference instance of <code>kobishop</code>
     */
    public static final Kobishop KOBISHOP = new Kobishop();

    /**
     * The table <code>kobishop.user</code>.
     */
    public final User USER = kobishop.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Kobishop() {
        super("kobishop", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
