/*
 * This file is generated by jOOQ.
*/
package kobishop;


import javax.annotation.Generated;

import kobishop.tables.User;


/**
 * Convenience access to all tables in kobishop
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kobishop.user</code>.
     */
    public static final User USER = kobishop.tables.User.USER;
}
