/*
 * This file is generated by jOOQ.
*/
package kobishop.tables.records;


import javax.annotation.Generated;

import kobishop.tables.Product;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record10<Integer, Integer, Integer, String, String, Integer, Integer, Integer, String, Byte> {

    private static final long serialVersionUID = -693214964;

    /**
     * Setter for <code>kobishop.product.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kobishop.product.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kobishop.product.typeId</code>.
     */
    public void setTypeid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kobishop.product.typeId</code>.
     */
    public Integer getTypeid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kobishop.product.brandId</code>.
     */
    public void setBrandid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>kobishop.product.brandId</code>.
     */
    public Integer getBrandid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kobishop.product.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kobishop.product.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kobishop.product.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kobishop.product.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kobishop.product.price</code>.
     */
    public void setPrice(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>kobishop.product.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kobishop.product.soldItems</code>.
     */
    public void setSolditems(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>kobishop.product.soldItems</code>.
     */
    public Integer getSolditems() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>kobishop.product.leftItems</code>.
     */
    public void setLeftitems(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>kobishop.product.leftItems</code>.
     */
    public Integer getLeftitems() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>kobishop.product.specs</code>.
     */
    public void setSpecs(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kobishop.product.specs</code>.
     */
    public String getSpecs() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kobishop.product.isDeleted</code>.
     */
    public void setIsdeleted(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>kobishop.product.isDeleted</code>.
     */
    public Byte getIsdeleted() {
        return (Byte) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, Integer, Integer, Integer, String, Byte> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, Integer, Integer, Integer, String, Byte> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Product.PRODUCT.TYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Product.PRODUCT.BRANDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Product.PRODUCT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Product.PRODUCT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Product.PRODUCT.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Product.PRODUCT.SOLDITEMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Product.PRODUCT.LEFTITEMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Product.PRODUCT.SPECS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return Product.PRODUCT.ISDELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getBrandid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSolditems();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getLeftitems();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSpecs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getIsdeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(Integer value) {
        setTypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value3(Integer value) {
        setBrandid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value6(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value7(Integer value) {
        setSolditems(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value8(Integer value) {
        setLeftitems(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value9(String value) {
        setSpecs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value10(Byte value) {
        setIsdeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6, Integer value7, Integer value8, String value9, Byte value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer id, Integer typeid, Integer brandid, String name, String description, Integer price, Integer solditems, Integer leftitems, String specs, Byte isdeleted) {
        super(Product.PRODUCT);

        set(0, id);
        set(1, typeid);
        set(2, brandid);
        set(3, name);
        set(4, description);
        set(5, price);
        set(6, solditems);
        set(7, leftitems);
        set(8, specs);
        set(9, isdeleted);
    }
}
